# Generated by Django 5.0 on 2023-12-24 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
