# Generated by Django 5.0 on 2023-12-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_delete_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=100)),
                ('news_desc', models.CharField(max_length=100)),
                ('news_image', models.FileField(default=None, max_length=250, null=True, upload_to='news/')),
            ],
        ),
    ]
